image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
environment:
  nodejs_version: "10"
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - ps: Install-Product node $env:nodejs_version
  - ps: IF ($env:APPVEYOR_REPO_BRANCH -eq "master") {$env:APPVEYOR_CACHE_SKIP_SAVE = "true"}
  - dotnet --version
  - dotnet restore
#  - choco install googlechrome  --ignore-checksums
build_script:
  - dotnet build
  - node --version
  - npm -g install npm@latest
  - cd OLBIL.OncologyWebApp\ClientApp
  - npm install
  - npm run build -- --prod
before_build:
  - appveyor-retry dotnet restore -v Minimal
test_script:
  - cd C:\projects\olbiloncology
  - dotnet test
cache:
  - packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - node_modules                        # local npm modules
  - '%APPDATA%\npm-cache'               # npm cache
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'  # project.json cache
  - '%LocalAppData%\NuGet\v3-cache'