BEGIN;

INSERT INTO olbil.Country(NameEs, NameEn, ISOCode2, ISOCode3)
VALUES
('Afganistán','Afghanistan', 'AF','AFG'),
('Albania','Albania', 'AL','ALB'),
('Alemania','Germany', 'DE','DEU'),
('Algeria','Algeria', 'DZ','DZA'),
('Andorra','Andorra', 'AD','AND'),
('Angola','Angola', 'AO','AGO'),
('Anguila','Anguilla', 'AI','AIA'),
('Antártida','Antarctica', 'AQ','ATA'),
('Antigua y Barbuda','Antigua and Barbuda', 'AG','ATG'),
('Antillas Neerlandesas','Netherlands Antilles', 'AN','ANT'),
('Arabia Saudita','Saudi Arabia', 'SA','SAU'),
('Argentina','Argentina', 'AR','ARG'),
('Armenia','Armenia', 'AM','ARM'),
('Aruba','Aruba', 'AW','ABW'),
('Australia','Australia', 'AU','AUS'),
('Austria','Austria', 'AT','AUT'),
('Azerbayán','Azerbaijan', 'AZ','AZE'),
('Bélgica','Belgium', 'BE','BEL'),
('Bahamas','Bahamas', 'BS','BHS'),
('Bahrein','Bahrain', 'BH','BHR'),
('Bangladesh','Bangladesh', 'BD','BGD'),
('Barbados','Barbados', 'BB','BRB'),
('Belice','Belize', 'BZ','BLZ'),
('Benín','Benin', 'BJ','BEN'),
('Bhután','Bhutan', 'BT','BTN'),
('Bielorrusia','Belarus', 'BY','BLR'),
('Birmania','Myanmar', 'MM','MMR'),
('Bolivia','Bolivia', 'BO','BOL'),
('Bosnia y Herzegovina','Bosnia and Herzegovina', 'BA','BIH'),
('Botsuana','Botswana', 'BW','BWA'),
('Brasil','Brazil', 'BR','BRA'),
('Brunéi','Brunei', 'BN','BRN'),
('Bulgaria','Bulgaria', 'BG','BGR'),
('Burkina Faso','Burkina Faso', 'BF','BFA'),
('Burundi','Burundi', 'BI','BDI'),
('Cabo Verde','Cape Verde', 'CV','CPV'),
('Camboya','Cambodia', 'KH','KHM'),
('Camerún','Cameroon', 'CM','CMR'),
('Canadá','Canada', 'CA','CAN'),
('Chad','Chad', 'TD','TCD'),
('Chile','Chile', 'CL','CHL'),
('China','China', 'CN','CHN'),
('Chipre','Cyprus', 'CY','CYP'),
('Ciudad del Vaticano','Vatican City State', 'VA','VAT'),
('Colombia','Colombia', 'CO','COL'),
('Comoras','Comoros', 'KM','COM'),
('Congo','Congo', 'CG','COG'),
('Congo','Congo', 'CD','COD'),
('Corea del Norte','North Korea', 'KP','PRK'),
('Corea del Sur','South Korea', 'KR','KOR'),
('Costa de Marfil','Ivory Coast', 'CI','CIV'),
('Costa Rica','Costa Rica', 'CR','CRI'),
('Croacia','Croatia', 'HR','HRV'),
('Cuba','Cuba', 'CU','CUB'),
('Dinamarca','Denmark', 'DK','DNK'),
('Dominica','Dominica', 'DM','DMA'),
('Ecuador','Ecuador', 'EC','ECU'),
('Egipto','Egypt', 'EG','EGY'),
('El Salvador','El Salvador', 'SV','SLV'),
('Emiratos Árabes Unidos','United Arab Emirates', 'AE','ARE'),
('Eritrea','Eritrea', 'ER','ERI'),
('Eslovaquia','Slovakia', 'SK','SVK'),
('Eslovenia','Slovenia', 'SI','SVN'),
('España','Spain', 'ES','ESP'),
('Estados Unidos de América','United States of America', 'US','USA'),
('Estonia','Estonia', 'EE','EST'),
('Etiopía','Ethiopia', 'ET','ETH'),
('Filipinas','Philippines', 'PH','PHL'),
('Finlandia','Finland', 'FI','FIN'),
('Fiyi','Fiji', 'FJ','FJI'),
('Francia','France', 'FR','FRA'),
('Gabón','Gabon', 'GA','GAB'),
('Gambia','Gambia', 'GM','GMB'),
('Georgia','Georgia', 'GE','GEO'),
('Ghana','Ghana', 'GH','GHA'),
('Gibraltar','Gibraltar', 'GI','GIB'),
('Granada','Grenada', 'GD','GRD'),
('Grecia','Greece', 'GR','GRC'),
('Groenlandia','Greenland', 'GL','GRL'),
('Guadalupe','Guadeloupe', 'GP','GLP'),
('Guam','Guam', 'GU','GUM'),
('Guatemala','Guatemala', 'GT','GTM'),
('Guayana Francesa','French Guiana', 'GF','GUF'),
('Guernsey','Guernsey', 'GG','GGY'),
('Guinea','Guinea', 'GN','GIN'),
('Guinea Ecuatorial','Equatorial Guinea', 'GQ','GNQ'),
('Guinea-Bissau','Guinea-Bissau', 'GW','GNB'),
('Guyana','Guyana', 'GY','GUY'),
('Haití','Haiti', 'HT','HTI'),
('Honduras','Honduras', 'HN','HND'),
('Hong kong','Hong Kong', 'HK','HKG'),
('Hungría','Hungary', 'HU','HUN'),
('India','India', 'IN','IND'),
('Indonesia','Indonesia', 'ID','IDN'),
('Irán','Iran', 'IR','IRN'),
('Irak','Iraq', 'IQ','IRQ'),
('Irlanda','Ireland', 'IE','IRL'),
('Isla Bouvet','Bouvet Island', 'BV','BVT'),
('Isla de Man','Isle of Man', 'IM','IMN'),
('Isla de Navidad','Christmas Island', 'CX','CXR'),
('Isla Norfolk','Norfolk Island', 'NF','NFK'),
('Islandia','Iceland', 'IS','ISL'),
('Islas Bermudas','Bermuda Islands', 'BM','BMU'),
('Islas Caimán','Cayman Islands', 'KY','CYM'),
('Islas Cocos (Keeling','Cocos (Keeling) Islands', 'CC','CCK'),
('Islas Cook','Cook Islands', 'CK','COK'),
('Islas de Åland','Åland Islands', 'AX','ALA'),
('Islas Feroe','Faroe Islands', 'FO','FRO'),
('Islas Georgias del Sur y Sandwich del Sur','South Georgia and the South Sandwich Islands', 'GS','SGS'),
('Islas Heard y McDonald','Heard Island and McDonald Islands', 'HM','HMD'),
('Islas Maldivas','Maldives', 'MV','MDV'),
('Islas Malvinas','Falkland Islands (Malvinas', 'FK','FLK'),
('Islas Marianas del Norte','Northern Mariana Islands', 'MP','MNP'),
('Islas Marshall','Marshall Islands', 'MH','MHL'),
('Islas Pitcairn','Pitcairn Islands', 'PN','PCN'),
('Islas Salomón','Solomon Islands', 'SB','SLB'),
('Islas Turcas y Caicos','Turks and Caicos Islands', 'TC','TCA'),
('Islas Ultramarinas Menores de Estados Unidos','United States Minor Outlying Islands', 'UM','UMI'),
('Islas Vírgenes Británicas','Virgin Islands', 'VG','VG'),
('Islas Vírgenes de los Estados Unidos','United States Virgin Islands', 'VI','VIR'),
('Israel','Israel', 'IL','ISR'),
('Italia','Italy', 'IT','ITA'),
('Jamaica','Jamaica', 'JM','JAM'),
('Japón','Japan', 'JP','JPN'),
('Jersey','Jersey', 'JE','JEY'),
('Jordania','Jordan', 'JO','JOR'),
('Kazajistán','Kazakhstan', 'KZ','KAZ'),
('Kenia','Kenya', 'KE','KEN'),
('Kirgizstán','Kyrgyzstan', 'KG','KGZ'),
('Kiribati','Kiribati', 'KI','KIR'),
('Kuwait','Kuwait', 'KW','KWT'),
('Líbano','Lebanon', 'LB','LBN'),
('Laos','Laos', 'LA','LAO'),
('Lesoto','Lesotho', 'LS','LSO'),
('Letonia','Latvia', 'LV','LVA'),
('Liberia','Liberia', 'LR','LBR'),
('Libia','Libya', 'LY','LBY'),
('Liechtenstein','Liechtenstein', 'LI','LIE'),
('Lituania','Lithuania', 'LT','LTU'),
('Luxemburgo','Luxembourg', 'LU','LUX'),
('México','Mexico', 'MX','MEX'),
('Mónaco','Monaco', 'MC','MCO'),
('Macao','Macao', 'MO','MAC'),
('Macedônia','Macedonia', 'MK','MKD'),
('Madagascar','Madagascar', 'MG','MDG'),
('Malasia','Malaysia', 'MY','MYS'),
('Malawi','Malawi', 'MW','MWI'),
('Mali','Mali', 'ML','MLI'),
('Malta','Malta', 'MT','MLT'),
('Marruecos','Morocco', 'MA','MAR'),
('Martinica','Martinique', 'MQ','MTQ'),
('Mauricio','Mauritius', 'MU','MUS'),
('Mauritania','Mauritania', 'MR','MRT'),
('Mayotte','Mayotte', 'YT','MYT'),
('Micronesia','Estados Federados de', 'FM','FSM'),
('Moldavia','Moldova', 'MD','MDA'),
('Mongolia','Mongolia', 'MN','MNG'),
('Montenegro','Montenegro', 'ME','MNE'),
('Montserrat','Montserrat', 'MS','MSR'),
('Mozambique','Mozambique', 'MZ','MOZ'),
('Namibia','Namibia', 'NA','NAM'),
('Nauru','Nauru', 'NR','NRU'),
('Nepal','Nepal', 'NP','NPL'),
('Nicaragua','Nicaragua', 'NI','NIC'),
('Niger','Niger', 'NE','NER'),
('Nigeria','Nigeria', 'NG','NGA'),
('Niue','Niue', 'NU','NIU'),
('Noruega','Norway', 'NO','NOR'),
('Nueva Caledonia','New Caledonia', 'NC','NCL'),
('Nueva Zelanda','New Zealand', 'NZ','NZL'),
('Omán','Oman', 'OM','OMN'),
('Países Bajos','Netherlands', 'NL','NLD'),
('Pakistán','Pakistan', 'PK','PAK'),
('Palau','Palau', 'PW','PLW'),
('Palestina','Palestine', 'PS','PSE'),
('Panamá','Panama', 'PA','PAN'),
('Papúa Nueva Guinea','Papua New Guinea', 'PG','PNG'),
('Paraguay','Paraguay', 'PY','PRY'),
('Perú','Peru', 'PE','PER'),
('Polinesia Francesa','French Polynesia', 'PF','PYF'),
('Polonia','Poland', 'PL','POL'),
('Portugal','Portugal', 'PT','PRT'),
('Puerto Rico','Puerto Rico', 'PR','PRI'),
('Qatar','Qatar', 'QA','QAT'),
('Reino Unido','United Kingdom', 'GB','GBR'),
('República Centroafricana','Central African Republic', 'CF','CAF'),
('República Checa','Czech Republic', 'CZ','CZE'),
('República Dominicana','Dominican Republic', 'DO','DOM'),
('Reunión','Réunion', 'RE','REU'),
('Ruanda','Rwanda', 'RW','RWA'),
('Rumanía','Romania', 'RO','ROU'),
('Rusia','Russia', 'RU','RUS'),
('Sahara Occidental','Western Sahara', 'EH','ESH'),
('Samoa','Samoa', 'WS','WSM'),
('Samoa Americana','American Samoa', 'AS','ASM'),
('San Bartolomé','Saint Barthélemy', 'BL','BLM'),
('San Cristóbal y Nieves','Saint Kitts and Nevis', 'KN','KNA'),
('San Marino','San Marino', 'SM','SMR'),
('San Martín (Francia','Saint Martin (French part', 'MF','MAF'),
('San Pedro y Miquelón','Saint Pierre and Miquelon', 'PM','SPM'),
('San Vicente y las Granadinas','Saint Vincent and the Grenadines', 'VC','VCT'),
('Santa Elena','Ascensión y Tristán de Acuña', 'SH','SHN'),
('Santa Lucía','Saint Lucia', 'LC','LCA'),
('Santo Tomé y Príncipe','Sao Tome and Principe', 'ST','STP'),
('Senegal','Senegal', 'SN','SEN'),
('Serbia','Serbia', 'RS','SRB'),
('Seychelles','Seychelles', 'SC','SYC'),
('Sierra Leona','Sierra Leone', 'SL','SLE'),
('Singapur','Singapore', 'SG','SGP'),
('Siria','Syria', 'SY','SYR'),
('Somalia','Somalia', 'SO','SOM'),
('Sri lanka','Sri Lanka', 'LK','LKA'),
('Sudáfrica','South Africa', 'ZA','ZAF'),
('Sudán','Sudan', 'SD','SDN'),
('Suecia','Sweden', 'SE','SWE'),
('Suiza','Switzerland', 'CH','CHE'),
('Surinám','Suriname', 'SR','SUR'),
('Svalbard y Jan Mayen','Svalbard and Jan Mayen', 'SJ','SJM'),
('Swazilandia','Swaziland', 'SZ','SWZ'),
('Tadjikistán','Tajikistan', 'TJ','TJK'),
('Tailandia','Thailand', 'TH','THA'),
('Taiwán','Taiwan', 'TW','TWN'),
('Tanzania','Tanzania', 'TZ','TZA'),
('Territorio Británico del Océano Índico','British Indian Ocean Territory', 'IO','IOT'),
('Territorios Australes y Antárticas Franceses','French Southern Territories', 'TF','ATF'),
('Timor Oriental','East Timor', 'TL','TLS'),
('Togo','Togo', 'TG','TGO'),
('Tokelau','Tokelau', 'TK','TKL'),
('Tonga','Tonga', 'TO','TON'),
('Trinidad y Tobago','Trinidad and Tobago', 'TT','TTO'),
('Tunez','Tunisia', 'TN','TUN'),
('Turkmenistán','Turkmenistan', 'TM','TKM'),
('Turquía','Turkey', 'TR','TUR'),
('Tuvalu','Tuvalu', 'TV','TUV'),
('Ucrania','Ukraine', 'UA','UKR'),
('Uganda','Uganda', 'UG','UGA'),
('Uruguay','Uruguay', 'UY','URY'),
('Uzbekistán','Uzbekistan', 'UZ','UZB'),
('Vanuatu','Vanuatu', 'VU','VUT'),
('Venezuela','Venezuela', 'VE','VEN'),
('Vietnam','Vietnam', 'VN','VNM'),
('Wallis y Futuna','Wallis and Futuna', 'WF','WLF'),
('Yemen','Yemen', 'YE','YEM'),
('Yibuti','Djibouti', 'DJ','DJI'),
('Zambia','Zambia', 'ZM','ZMB'),
('Zimbabue','Zimbabwe', 'ZW','ZWE')
ON CONFLICT DO NOTHING;

COMMIT;
