workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run:
          name: Installing Node
          command: curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -y nodejs
      - run:
          name: Restore solution
          command: dotnet restore
      - run:
          name: Build solution
          command: dotnet build
      - run:
          name: Run tests
          command: dotnet test --no-build OLBIL.OncologyTests
