version: 2
jobs:
  build:
    docker:
      - image: node:10-slim
      - image: microsoft/dotnet:2.2-sdk

    steps:
      - checkout
      - run:
          name: Restore solution
          command: dotnet restore
      - run:
          name: Build solution
          command: dotnet build
      - run:
          name: Run tests
          command: dotnet test --no-build OLBIL.DomainTests
